### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by nathanielperales** [blue-mantis/BM-Infinite-Scroll#1]
Hey there,

I'm getting a Uncaught RangeError: Maximum call stack size exceeded when paginating. Please take a look here: https://allthingscomedy.com/podcast/skeptic-tank/335-pranks-for-the-memories-daniel_sloss

The code I'm using is: 

`{{ paginate|infinitescroll(containerSelector="#other-episodes", itemSelector=".other-episodes-wrapper", loadingMessage="", finishedMessage="You've loaded all the episodes ✌", loadingImage="/images/ellipse.gif" ) }}`

It was working before no problem and then all of a sudden got that.

Any help would be greatly appreciated.

**Comment by auralon** [comment]
Hi @nathanielperales,

So, based on a very quick test, it would seem that this is in some way related to the `jquery.ajax-cross-origin.min.js` plugin, though how or why this cross-origin jquery plugin is breaking things I'm not certain, without more testing.

The full stack error in the console is:

    jquery.min.js:2 Uncaught RangeError: Maximum call stack size exceeded
        at Function.n.extend.n.fn.extend (jquery.min.js:2)
        at Function.n.extend.n.fn.extend (jquery.min.js:2)
        at xb (jquery.min.js:4)
        at Function.ajaxSetup (jquery.min.js:4)
        at Function.jQuery.ajax [as ajaxOrig] (VM2591 jquery.ajax-cross-origin.min.js:16)
        at Function.jQuery.ajax [as ajaxOrig] (VM2591 jquery.ajax-cross-origin.min.js:17)

I'm not entirely certain why this would suddenly break, if it has worked previously.  I wonder... have there been any recent updates to the site, that might have introduced this bug?

Anyway, with minimal investigation I see that the infinite scroll plugin still works on the blog, so the breakage is unique to this podcast index page.

I actually managed to get the infinite scroll plugin to load items on the podcast index page without issue, by simply blocking the `allthingscomedy.com/js/jquery.ajax-cross-origin.min.js` resource using Chrome Web Dev Tools.

Can you disable the cross origin plugin? What is its purpose exactly?  I can see that the cross origin plugin is included on the blog index too, so not sure why the conflict only appears on the podcast index.

I realise this isn't a fix, but it at least offers something to go on, pinpointing the problem to a degree.

**Comment by nathanielperales** [comment]
Hey Keith,

Thanks for your help. I commented out that file and it seems to be working fine now. It’s been about a year since I developed the site, so I’m not remembering why that file was there in the first place. I’m going to leave it like this for now and see if something breaks haha.

Thanks again,

Nathaniel Perales
http://nathanielperales.com

**Comment by auralon** [comment]
No problem.  If you need anything else or work out why the error occurs, I'd be interested to find out.  In the meantime I'm going to close this issue for now.

All the best,
Keith
